services:
  py-test:
    container_name: py-test
    build: .
    #ports:
    #  - "80:80"
    volumes:
      - ./app:/usr/src/app

    networks:
      - frontend

networks:
  frontend:
    external: true

